"""modelo de custodia inicial

Revision ID: b64296a4c597
Revises: 
Create Date: 2026-10-06 00:26:30.290781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64296a4c597'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('compra', 'fabricacion', name='tipo_solicitud', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=40), nullable=True),
    sa.Column('pedida_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llega_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'recibida', 'fallida', name='estado_solicitud', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitudes'))
    )
    op.create_index('ix_solicitudes_estado_llega_en', 'solicitudes', ['estado', 'llega_en'], unique=False)
    op.create_index(op.f('ix_solicitudes_sku'), 'solicitudes', ['sku'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('orden_externa_id', sa.String(length=60), nullable=True),
    sa.Column('comprador_nombre', sa.String(length=120), nullable=True),
    sa.Column('comprador_email', sa.String(length=120), nullable=True),
    sa.Column('transaccion_id', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.Enum('pendiente_pago', 'pagada', 'cancelada', 'error', name='estado_venta', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pagada_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas')),
    sa.UniqueConstraint('transaccion_id', name=op.f('uq_ventas_transaccion_id'))
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('cantidad_inicial', sa.Integer(), nullable=False),
    sa.Column('vence_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origen', sa.Enum('farma_central', 'distribuidora', 'produccion', name='origen_lote', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('origen_grupo', sa.Integer(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('lote_proveedor', sa.String(length=60), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], name=op.f('fk_lotes_solicitud_id_solicitudes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lotes')),
    sa.UniqueConstraint('codigo', name=op.f('uq_lotes_codigo')),
    sa.UniqueConstraint('solicitud_id', name=op.f('uq_lotes_solicitud_id'))
    )
    op.create_index(op.f('ix_lotes_sku'), 'lotes', ['sku'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('espacio_actual', sa.Enum('checkIn', 'bodega', 'cold', 'buffer', 'packaging', 'checkOut', 'quarantine', name='espacio', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('estado', sa.Enum('en_stock', 'consumida', 'despachada', 'vencida', 'cuarentena', name='estado_unidad', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('vence_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_unidades_lote_id_lotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades'))
    )
    op.create_index(op.f('ix_unidades_lote_id'), 'unidades', ['lote_id'], unique=False)
    op.create_index('ix_unidades_sku_estado', 'unidades', ['sku', 'estado'], unique=False)
    op.create_table('consumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.String(length=40), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_consumos_lote_id_lotes')),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], name=op.f('fk_consumos_solicitud_id_solicitudes')),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], name=op.f('fk_consumos_unidad_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumos')),
    sa.UniqueConstraint('unidad_id', name=op.f('uq_consumos_unidad_id'))
    )
    op.create_index(op.f('ix_consumos_lote_id'), 'consumos', ['lote_id'], unique=False)
    op.create_index(op.f('ix_consumos_solicitud_id'), 'consumos', ['solicitud_id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.String(length=40), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('recepcion', 'traslado', 'consumo', 'generacion', 'venta', 'despacho', 'vencimiento', 'cuarentena', name='tipo_movimiento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('desde', sa.Enum('checkIn', 'bodega', 'cold', 'buffer', 'packaging', 'checkOut', 'quarantine', name='espacio_desde', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('hacia', sa.Enum('checkIn', 'bodega', 'cold', 'buffer', 'packaging', 'checkOut', 'quarantine', name='espacio_hacia', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_movimientos_lote_id_lotes')),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], name=op.f('fk_movimientos_solicitud_id_solicitudes')),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], name=op.f('fk_movimientos_unidad_id_unidades')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_movimientos_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos'))
    )
    op.create_index(op.f('ix_movimientos_fecha'), 'movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_lote_id'), 'movimientos', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimientos_unidad_id'), 'movimientos', ['unidad_id'], unique=False)
    op.create_table('venta_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.String(length=40), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'despachada', name='estado_despacho', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('despachada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_venta_unidades_lote_id_lotes')),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], name=op.f('fk_venta_unidades_unidad_id_unidades')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_venta_unidades_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_unidades')),
    sa.UniqueConstraint('unidad_id', name=op.f('uq_venta_unidades_unidad_id'))
    )
    op.create_index(op.f('ix_venta_unidades_lote_id'), 'venta_unidades', ['lote_id'], unique=False)
    op.create_index(op.f('ix_venta_unidades_venta_id'), 'venta_unidades', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_unidades_venta_id'), table_name='venta_unidades')
    op.drop_index(op.f('ix_venta_unidades_lote_id'), table_name='venta_unidades')
    op.drop_table('venta_unidades')
    op.drop_index(op.f('ix_movimientos_unidad_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_lote_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_fecha'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_consumos_solicitud_id'), table_name='consumos')
    op.drop_index(op.f('ix_consumos_lote_id'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_index('ix_unidades_sku_estado', table_name='unidades')
    op.drop_index(op.f('ix_unidades_lote_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_lotes_sku'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_solicitudes_sku'), table_name='solicitudes')
    op.drop_index('ix_solicitudes_estado_llega_en', table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
